version: '3.8'

services:
  app:
    # Using the devcontainer.json to define the container
    # This is used when you need additional services
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "3.11-bookworm"
    
    volumes:
      # Mount the project
      - ..:/workspace:cached
      
      # Preserve bash history
      - ~/.devcontainer-bash_history:/home/vscode/.bash_history:cached
      
      # Share SSH keys (read-only)
      - ~/.ssh:/home/vscode/.ssh:ro
      
      # Docker socket for Docker-in-Docker
      # - /var/run/docker.sock:/var/run/docker.sock
    
    environment:
      - CLAUDE_HOOKS_ENABLED=true
      - CLAUDE_PROJECT_ROOT=/workspace
      - CLAUDE_MEMORY_BANK_OPTIMIZED=true
    
    # Overrides default command so things don't shut down after the process ends
    command: sleep infinity
    
    # Uncomment to connect as root instead
    # user: root
    
    networks:
      - devcontainer-network
    
    # Uncomment if you need specific capabilities
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

  # Example: Add a PostgreSQL database
  # db:
  #   image: postgres:15
  #   restart: unless-stopped
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: developer
  #     POSTGRES_PASSWORD: devpassword
  #     POSTGRES_DB: devdb
  #   networks:
  #     - devcontainer-network

  # Example: Add Redis cache
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - devcontainer-network

  # Example: Add Elasticsearch
  # elasticsearch:
  #   image: elasticsearch:8.11.0
  #   restart: unless-stopped
  #   environment:
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - xpack.security.enabled=false
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data
  #   networks:
  #     - devcontainer-network

networks:
  devcontainer-network:
    driver: bridge

volumes:
  # postgres-data:
  # redis-data:
  # elasticsearch-data: